### ISSUE TITLE
Couldn't clear the device buffer

### ISSUE THREAD

**Issue by Amplifier-seller** [dongdawn/rid#3]
Hello! When I run the ALA-2 example, the job stopped unexpectedly during iter.000001:
```
2023-08-17 15:12:00,908 iter 000001 task 00: make_enhc
2023-08-17 15:12:00,917                      use conf of iter iter.000000 walker 000
2023-08-17 15:12:00,939                      use NN model(s): graph.000.pb,graph.001.pb,graph.002.pb,graph.003.pb
2023-08-17 15:12:00,939                      set trust l1 and l2: 2.000000 3.000000
2023-08-17 15:12:00,940 iter 000001 task 01: run_enhc
2023-08-17 15:12:00,947 f115.hn.org 000 000: gmx grompp 1> gmx_grompp.log 2> gmx_grompp.log 
# job 87830 submitted, dir /pubhome/gwchen02/data/rid/ala2.rid/iter.000001/00.enhcMD/000 
Traceback (most recent call last):
  File "rid.py", line 375, in <module>
    _main()
  File "rid.py", line 371, in _main
    run_iter (args.JSON, args.models)
  File "rid.py", line 303, in run_iter
    run_enhc  (ii, json_file)
  File "rid.py", line 194, in run_enhc
    exec_batch(gmx_run_cmd, enhc_thread, 1, all_task, task_args = None, time_limit = batch_time_limit, modules = batch_modules, sources = batch_sources)
  File "/pubhome/gwchen02/data/rid/ala2.rid/lib/batch_exec.py", line 139, in exec_batch
    raise RuntimeError("find terminated job")
RuntimeError: find terminated job
```
So I manually run the command `gmx mdrun -nt 4  -plumed plumed.dat` in the `sub` script in `ala2.rid/iter.000001/00.enhcMD/000`, and it sent a error message: 
```
2023-08-17 15:14:22.022627: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: NVIDIA GeForce RTX 3090 major: 8 minor: 6 memoryClockRate(GHz): 1.695
pciBusID: 0000:3b:00.0
2023-08-17 15:14:22.022767: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 1 with properties: 
name: NVIDIA GeForce RTX 3090 major: 8 minor: 6 memoryClockRate(GHz): 1.695
pciBusID: 0000:d8:00.0
2023-08-17 15:14:22.022798: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
2023-08-17 15:14:22.022806: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10
2023-08-17 15:14:22.022814: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10
2023-08-17 15:14:22.022822: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10
2023-08-17 15:14:22.022828: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10
2023-08-17 15:14:22.022836: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10
2023-08-17 15:14:22.022844: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2023-08-17 15:14:22.023271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0, 1
2023-08-17 15:14:22.023298: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-08-17 15:14:22.023305: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 1 
2023-08-17 15:14:22.023310: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N N 
2023-08-17 15:14:22.023315: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 1:   N N 
2023-08-17 15:14:22.023690: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 22749 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:3b:00.0, compute capability: 8.6)
2023-08-17 15:14:22.023818: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 22812 MB memory) -> physical GPU (device: 1, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:d8:00.0, compute capability: 8.6)

-------------------------------------------------------
Program:     gmx mdrun, version 2020.2-MODIFIED
Source file: src/gromacs/gpu_utils/devicebuffer.cuh (line 207)
Function:    clearDeviceBufferAsync(ValueType**, size_t, size_t, CommandStream)::<lambda()> [with ValueType = float]

Assertion failed:
Condition: stat == cudaSuccess
Couldn't clear the device buffer

For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
-------------------------------------------------------
```
How can I deal with that? Thank you!

**Comment by xingyu-200** [comment]
Hello? Have you solved this problem? I met this today.
2024-10-23 14:36:00.613360: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2024-10-23 14:36:00.618868: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2024-10-23 14:36:00.713063: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2024-10-23 14:36:00.713127: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (master): /proc/driver/nvidia/version does not exist
Invalid argument: Expects arg[0] to be double but float is provided

**Comment by xingyu-200** [comment]
Hello! Have you solved this question? I met this today.
`2024-10-23 14:36:00.613360: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2024-10-23 14:36:00.618868: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2024-10-23 14:36:00.713063: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2024-10-23 14:36:00.713127: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (master): /proc/driver/nvidia/version does not exist
Invalid argument: Expects arg[0] to be double but float is provided
`

**Comment by Amplifier-seller** [comment]
> Hello! Have you solved this question? I met this today. `2024-10-23 14:36:00.613360: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA 2024-10-23 14:36:00.618868: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1 2024-10-23 14:36:00.713063: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected 2024-10-23 14:36:00.713127: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (master): /proc/driver/nvidia/version does not exist Invalid argument: Expects arg[0] to be double but float is provided `

Hello! I managed to contact the developer, and was informed that `rid` has been transplanted to another git repository: https://github.com/deepmodeling/rid-kit . You can try this one.

**Comment by xingyu-200** [comment]
> > Hello! Have you solved this question? I met this today. `2024-10-23 14:36:00.613360: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA 2024-10-23 14:36:00.618868: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1 2024-10-23 14:36:00.713063: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected 2024-10-23 14:36:00.713127: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (master): /proc/driver/nvidia/version does not exist Invalid argument: Expects arg[0] to be double but float is provided `
> 
> Hello! I managed to contact the developer, and was informed that `rid` has been transplanted to another git repository: https://github.com/deepmodeling/rid-kit . You can try this one.

Yes! I have solved this problem! Thanks so much !!!
